services:
  cloud-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    container_name: cloud-backend
    env_file:
      - ./.env
    depends_on:
      - cloud-postgres
    ports:
      - '8000:${PORT}'
    networks:
      - trumpet-proxy

  cloud-postgres:
    image: postgres:15-alpine
    container_name: cloud-postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgresql/cloud/data:/var/lib/postgresql/data/
    networks:
      - trumpet-proxy

  openfga:
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    image: openfga/openfga:v1.8
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://${OPENFGA_POSTGRES_ADMIN_USER}:${OPENFGA_POSTGRES_ADMIN_USER_PASSWORD}@openfga-postgres:5432/${OPENFGA_POSTGRES_DB}?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    command: run
#    ports:
#        - "8080:8080"
#        - "8081:8081"
#        - "3001:3000"
    networks:
      - trumpet-proxy

networks:
  trumpet-proxy:
    external: true
