services:
  cloud-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    container_name: cloud-backend

    env_file:
      - ./.env
    depends_on:
      - cloud-postgres
      - fl-core-agg
    ports:
      - '9000:8000'

  cloud-postgres:
    image: postgres:15-alpine
    container_name: cloud-postgres
    restart: always
    environment:
      POSTGRES_DB: 'trumpet-cloud'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - ./docker/postgresql/cloud/data:/var/lib/postgresql/data/

  fl-core-agg:
    image: "njnur/fl-core-agg:0.0.1"
    restart: on-failure
    container_name: fl-core-agg
    ports:
      - "9003:8000"
      - "9083:8080"
    environment:
      NODE_ID: 0
