"""add organization id in studyAgreementResults

Revision ID: 1b2a39e88690
Revises: d188f3064c7a
Create Date: 2025-11-05 11:29:57.302736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2a39e88690'
down_revision: Union[str, None] = 'd188f3064c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_agreement_results', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_agreement_results', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_agreement_results', type_='foreignkey')
    op.drop_column('study_agreement_results', 'organization_id')
    # ### end Alembic commands ###
