"""add pet_config to study agreement

Revision ID: 2eb38582995f
Revises: 39d2305f1f5e
Create Date: 2025-07-14 20:01:04.855803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb38582995f'
down_revision: Union[str, None] = '39d2305f1f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_agreements', sa.Column('pet_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_agreements', 'pet_config')
    # ### end Alembic commands ###
