"""add pet_config to study agreement

Revision ID: 5b8b3139e5b4
Revises: 39d2305f1f5e
Create Date: 2025-07-15 18:19:59.151504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8b3139e5b4'
down_revision: Union[str, None] = '39d2305f1f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_agreements', sa.Column('pet_config', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_agreements', 'pet_config')
    # ### end Alembic commands ###
