"""Add new lebel for SBRT

Revision ID: 969b750a6805
Revises: cd324987b324
Create Date: 2025-10-23 18:38:08.362847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '969b750a6805'
down_revision: Union[str, None] = 'cd324987b324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_label_enum',
        new_values=['HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS', 'NSCLC_DURATION_MONTHS', 'SBRT_SURVIVAL'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='label')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_label_enum',
        new_values=['HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS', 'NSCLC_DURATION_MONTHS'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='label')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
