"""add don_auth_token field in organisatino table

Revision ID: acfb9e400064
Revises: 1b2a39e88690
Create Date: 2025-11-26 16:52:46.739537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfb9e400064'
down_revision: Union[str, None] = '1b2a39e88690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('don_auth_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'don_auth_token')
    # ### end Alembic commands ###
