"""Add lebel enum

Revision ID: b7aabb1b40c9
Revises: fa5e8654e91e
Create Date: 2025-09-22 15:37:36.281143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'b7aabb1b40c9'
down_revision: Union[str, None] = 'fa5e8654e91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_label_enum',
        new_values=['HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS', 'NSCLC_DURATION_MONTHS'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='label')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_label_enum',
        new_values=['HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='label')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
