"""First migration

Revision ID: b8c40fd3727c
Revises: 
Create Date: 2025-06-20 17:42:18.021562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8c40fd3727c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('active', 'paused', 'completed', name='studies_status_enum').create(op.get_bind())
    sa.Enum('pending', 'completed', name='study_agreement_results_status_enum').create(op.get_bind())
    sa.Enum('governance', 'data_owner', 'researcher', name='organizations_type_enum').create(op.get_bind())
    sa.Enum('approved', 'disapproved', 'blocked', 'pending', name='organizations_status_enum').create(op.get_bind())
    sa.Enum('researcher', 'data_owner', name='organization_study_agreements_organization_type_enum').create(op.get_bind())
    sa.Enum('public', 'confidential', 'highly_confidential', name='datasets_privacy_level_enum').create(op.get_bind())
    sa.Enum('pending', 'approved', 'disapproved', name='study_agreements_status_enum').create(op.get_bind())
    sa.Enum('NN_HNC', 'NN_HNC_NECRO_JAW', 'NN_HNC_DYSPHAGIA', 'NN_HNC_ORAL_MUCOSITIS', 'REG_LOG_HNC', 'REG_LOG_HNC_NECRO_JAW', 'REG_LOG_HNC_DYSPHAGIA', 'REG_LOG_HNC_ORAL_MUCOSITIS', name='study_agreements_model_enum').create(op.get_bind())
    sa.Enum('None', 'CDC_DP', 'ThHE', name='study_agreements_pet_enum').create(op.get_bind())
    sa.Enum('approved', 'disapproved', 'blocked', 'pending', 'deleted', name='users_status_enum').create(op.get_bind())
    sa.Enum('custom', 'legal', 'personal', 'other', name='files_type_enum').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('approved', 'disapproved', 'blocked', 'pending', 'deleted', name='users_status_enum', create_type=False), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('statistics', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('privacy_level', postgresql.ENUM('public', 'confidential', 'highly_confidential', name='datasets_privacy_level_enum', create_type=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('custom', 'legal', 'personal', 'other', name='files_type_enum', create_type=False), nullable=True),
    sa.Column('buffer', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('approved', 'disapproved', 'blocked', 'pending', name='organizations_status_enum', create_type=False), nullable=True),
    sa.Column('type', postgresql.ENUM('governance', 'data_owner', 'researcher', name='organizations_type_enum', create_type=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('host'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'paused', 'completed', name='studies_status_enum', create_type=False), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=True),
    sa.Column('participants', sa.String(length=255), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('pet', postgresql.ENUM('None', 'CDC_DP', 'ThHE', name='study_agreements_pet_enum', create_type=False), nullable=True),
    sa.Column('model', postgresql.ENUM('NN_HNC', 'NN_HNC_NECRO_JAW', 'NN_HNC_DYSPHAGIA', 'NN_HNC_ORAL_MUCOSITIS', 'REG_LOG_HNC', 'REG_LOG_HNC_NECRO_JAW', 'REG_LOG_HNC_DYSPHAGIA', 'REG_LOG_HNC_ORAL_MUCOSITIS', name='study_agreements_model_enum', create_type=False), nullable=True),
    sa.Column('legal', sa.String(length=30), nullable=True),
    sa.Column('study_privacy_budget', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'disapproved', name='study_agreements_status_enum', create_type=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_study_agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('study_agreement_id', sa.Integer(), nullable=True),
    sa.Column('organization_type', postgresql.ENUM('researcher', 'data_owner', name='organization_study_agreements_organization_type_enum', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'disapproved', name='study_agreements_status_enum', create_type=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['study_agreement_id'], ['study_agreements.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_agreement_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('study_agreement_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['study_agreement_id'], ['study_agreements.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_agreement_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_agreement_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_agreement_id'], ['study_agreements.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_agreement_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_agreement_id', sa.Integer(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'completed', name='study_agreement_results_status_enum', create_type=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_agreement_id'], ['study_agreements.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_agreement_results')
    op.drop_table('study_agreement_queries')
    op.drop_table('study_agreement_datasets')
    op.drop_table('organization_study_agreements')
    op.drop_table('user_roles')
    op.drop_table('study_users')
    op.drop_table('study_agreements')
    op.drop_table('organization_users')
    op.drop_table('studies')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('files')
    op.drop_table('datasets')
    op.drop_table('users')
    sa.Enum('custom', 'legal', 'personal', 'other', name='files_type_enum').drop(op.get_bind())
    sa.Enum('approved', 'disapproved', 'blocked', 'pending', 'deleted', name='users_status_enum').drop(op.get_bind())
    sa.Enum('None', 'CDC_DP', 'ThHE', name='study_agreements_pet_enum').drop(op.get_bind())
    sa.Enum('NN_HNC', 'NN_HNC_NECRO_JAW', 'NN_HNC_DYSPHAGIA', 'NN_HNC_ORAL_MUCOSITIS', 'REG_LOG_HNC', 'REG_LOG_HNC_NECRO_JAW', 'REG_LOG_HNC_DYSPHAGIA', 'REG_LOG_HNC_ORAL_MUCOSITIS', name='study_agreements_model_enum').drop(op.get_bind())
    sa.Enum('pending', 'approved', 'disapproved', name='study_agreements_status_enum').drop(op.get_bind())
    sa.Enum('public', 'confidential', 'highly_confidential', name='datasets_privacy_level_enum').drop(op.get_bind())
    sa.Enum('researcher', 'data_owner', name='organization_study_agreements_organization_type_enum').drop(op.get_bind())
    sa.Enum('approved', 'disapproved', 'blocked', 'pending', name='organizations_status_enum').drop(op.get_bind())
    sa.Enum('governance', 'data_owner', 'researcher', name='organizations_type_enum').drop(op.get_bind())
    sa.Enum('pending', 'completed', name='study_agreement_results_status_enum').drop(op.get_bind())
    sa.Enum('active', 'paused', 'completed', name='studies_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
