"""changes field in study agreements

Revision ID: bf5e948d768f
Revises: f5e4223f4262
Create Date: 2025-08-08 14:58:08.275133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf5e948d768f'
down_revision: Union[str, None] = 'f5e4223f4262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS', name='study_agreements_label_enum').create(op.get_bind())
    op.add_column('study_agreements', sa.Column('label', postgresql.ENUM('HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS', name='study_agreements_label_enum', create_type=False), nullable=True))
    op.drop_column('study_agreements', 'study_privacy_budget')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_model_enum',
        new_values=['REG_LOG', 'NN'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='model')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_model_enum',
        new_values=['NN_HNC', 'NN_HNC_NECRO_JAW', 'NN_HNC_DYSPHAGIA', 'NN_HNC_ORAL_MUCOSITIS', 'REG_LOG_HNC', 'REG_LOG_HNC_NECRO_JAW', 'REG_LOG_HNC_DYSPHAGIA', 'REG_LOG_HNC_ORAL_MUCOSITIS'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='model')],
        enum_values_to_rename=[],
    )
    op.add_column('study_agreements', sa.Column('study_privacy_budget', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('study_agreements', 'label')
    sa.Enum('HNC', 'HNC_NECRO_JAW', 'HNC_DYSPHAGIA', 'HNC_ORAL_MUCOSITIS', name='study_agreements_label_enum').drop(op.get_bind())
    # ### end Alembic commands ###
