"""add next_training_time column to study_agreements table

Revision ID: cd324987b324
Revises: 1fb779383558
Create Date: 2025-10-10 17:34:18.234190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd324987b324'
down_revision: Union[str, None] = '1fb779383558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_agreements', sa.Column('next_training_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_agreements', 'next_training_time')
    # ### end Alembic commands ###
