"""add three more pet methods

Revision ID: d188f3064c7a
Revises: 969b750a6805
Create Date: 2025-11-02 21:05:23.354388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'd188f3064c7a'
down_revision: Union[str, None] = '969b750a6805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_pet_enum',
        new_values=['None', 'CDC_DP', 'ThHE', 'MKHE_FED_AVG', 'PBACC_AGG_DDP', 'PBACC_AGG_SVT'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='pet')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='study_agreements_pet_enum',
        new_values=['None', 'CDC_DP', 'ThHE'],
        affected_columns=[TableReference(table_schema='public', table_name='study_agreements', column_name='pet')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
