"""alter purpose data type

Revision ID: fd0833bcfa90
Revises: 16e284e8cd63
Create Date: 2025-07-28 12:50:59.821684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0833bcfa90'
down_revision: Union[str, None] = '16e284e8cd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_agreements', 'purpose',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_agreements', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
