"""add use case to study agreements

Revision ID: fd52d894f0d6
Revises: 51166e759507
Create Date: 2025-07-28 18:08:12.249514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd52d894f0d6'
down_revision: Union[str, None] = '51166e759507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('HNC', 'SBRT', 'NSCLC', name='study_agreements_use_case_enum').create(op.get_bind())
    op.add_column('study_agreements', sa.Column('use_case', postgresql.ENUM('HNC', 'SBRT', 'NSCLC', name='study_agreements_use_case_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_agreements', 'use_case')
    sa.Enum('HNC', 'SBRT', 'NSCLC', name='study_agreements_use_case_enum').drop(op.get_bind())
    # ### end Alembic commands ###
